In [9]:
import numpy as np

In [11]:
x = np.array ([[10,20],[30,40]])
squarex= x*x
print (squarex)
addedx = x + 100
print (addedx)
multix = x*5
print(multix)
sqx = np.sqrt(x)
print(sqx)

[[ 100  400]
 [ 900 1600]]
[[110 120]
 [130 140]]
[[ 50 100]
 [150 200]]
[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [31]:
x = np.array(range(10,21))
y = float(11) // float(9)
print (y)
multix = x
print (multix)

1.0
[10 11 12 13 14 15 16 17 18 19 20]


In [50]:
sevenar = np.array([[3,6,9],[12,15,18],[21,24,27]])
numar = np.array([[11,12,13],[14,15,16],[17,18,19]])
mular= sevenar*numar
print (mular)
type (mular)

[[ 33  72 117]
 [168 225 288]
 [357 432 513]]


numpy.ndarray

In [62]:
loadednp = np.array([np.load("process1.npy"),np.load("process2.npy"),np.load("process3.npy"),np.load("process4.npy"),np.load("process5.npy")])
print(loadednp)
type (loadednp)
loadednp.shape

[[[52 12 81  0 58]]

 [[96  4 61 16 43]]

 [[38 96 45 17 58]]

 [[97 21 22 25  6]]

 [[77  6 19  2 74]]]


(5, 1, 5)

In [70]:
array1 = np.load("process1.npy")
print (array1)
array1.shape
a = array1[0, :]
a.shape
print (a)

[[52 12 81  0 58]]
[52 12 81  0 58]


In [77]:
array1 = np.load("process1.npy")
a = array1[0, :]
array2 = np.load("process2.npy")
b = array2[0, :]
array3 = np.load("process3.npy")
c = array3[0, :]
array4 = np.load("process4.npy")
d = array4[0, :]
array5 = np.load("process5.npy")
e = array5[0, :]
refinedarray = np.array([a,b,c,d,e])
print (refinedarray)
refinedarray.shape
x= refinedarray

[[52 12 81  0 58]
 [96  4 61 16 43]
 [38 96 45 17 58]
 [97 21 22 25  6]
 [77  6 19  2 74]]


In [81]:
print(numpy.mean(x[:, 0]))
print(numpy.mean(x[:, 1]))
print(numpy.mean(x[:, 2]))
print(numpy.mean(x[:, 3]))
print(numpy.mean(x[:, 4]))

72.0
27.8
45.6
12.0
47.8
